### ISSUE TITLE
class Player

### ISSUE THREAD

**Issue by AbdooTolba** [AbdooTolba/OOP-Project-BoardGamesMangmentSystem#3]
- [ ] Make a Player class 

has(

- [x] name,

- [ ] enum stauts if the player is in or out the game
- [x]  , score 
- [x] and array list for items. 
- [x] With all getters and settter, 
- [x] a def cstr and cstr with this for each variable 
- [x] method to change player out/in the game 
- [x] and array list for history of player!

- [x] and a method to add, sub, div or mul the score/value

- [ ] another method to add or remove an item from player from the array list

**Comment by amr-elbana** [comment]
We don't need a method to change player status "i make it by a boolean variabe can be be changed by set_method "

we don't need a method to add or remove an item from the array list
